version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/examples/default"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"

  # Enable version updates for Docker
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit_message:
      prefix: "chore"
